from flask import Flask, render_template, request, redirect, url_for, flash
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import os
from supabase import create_client, Client

app = Flask(__name__, instance_relative_config=False)  # Disable instance folder for serverless
app.secret_key = os.environ.get('SECRET_KEY', 'super_secret_key_for_scope_nexa_ai')

# Initialize Supabase client if credentials are provided
supabase_url = os.environ.get('SUPABASE_URL')
supabase_key = os.environ.get('SUPABASE_ANON_KEY')
if supabase_url and supabase_key:
    supabase: Client = create_client(supabase_url, supabase_key)
else:
    supabase = None

# Check for database URL: prefer Supabase DB URL, then Vercel Postgres, then standard DATABASE_URL, fallback to SQLite
database_url = os.environ.get('SUPABASE_DB_URL') or os.environ.get('POSTGRES_URL') or os.environ.get('DATABASE_URL') or 'sqlite:///scope_nexa.db'
# SQLAlchemy expects 'postgresql://' instead of 'postgres://' generated by older platforms
if database_url.startswith('postgres://'):
    database_url = database_url.replace('postgres://', 'postgresql://', 1)

app.config['SQLALCHEMY_DATABASE_URI'] = database_url
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

class Contact(db.Model):
    __tablename__ = 'contacts'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    company_size = db.Column(db.String(50))
    industry = db.Column(db.String(100))
    departments = db.Column(db.String(255))
    readiness_level = db.Column(db.String(50))
    message = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Assessment(db.Model):
    __tablename__ = 'assessments'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    company = db.Column(db.String(100))
    score = db.Column(db.Integer)
    details = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

# Check if running on Vercel (read-only filesystem)
IS_VERCEL = "VERCEL" in os.environ

# Ensure tables are created securely within application context
# On Vercel, db.create_all() might fail if using SQLite on a read-only filesystem
with app.app_context():
    try:
        db.create_all()
    except Exception as e:
        print(f"Database initialization skipped or failed: {e}")
        if not IS_VERCEL:
            # Re-raise if not on Vercel to help local debugging
            raise e

@app.route('/')
def home():
    return render_template('home.html', title='Home')

@app.route('/about')
def about():
    return render_template('about.html', title='About Us')

@app.route('/services')
def services():
    return render_template('services.html', title='Services')

@app.route('/software-solutions')
def software_solutions():
    return render_template('software_solutions.html', title='Software Based AI Solutions')

@app.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        company_size = request.form.get('company_size')
        industry = request.form.get('industry')
        departments = request.form.getlist('departments')
        deps_str = ", ".join(departments) if departments else request.form.get('departments_text', '')
        readiness_level = request.form.get('readiness_level')
        message = request.form.get('message')
        
        new_contact = Contact(
            name=name, email=email, company_size=company_size, 
            industry=industry, departments=deps_str, 
            readiness_level=readiness_level, message=message
        )
        db.session.add(new_contact)
        db.session.commit()
        
        flash('Thank you for reaching out! We will contact you soon.', 'success')
        return redirect(url_for('contact'))
        
    return render_template('contact.html', title='Contact')

@app.route('/assessment', methods=['POST'])
def assessment():
    name = request.form.get('name')
    email = request.form.get('email')
    company = request.form.get('company')
    
    score = 0
    q1 = request.form.get('q1', '0')
    q2 = request.form.get('q2', '0')
    q3 = request.form.get('q3', '0')
    
    try:
        score = int(q1) + int(q2) + int(q3)
    except ValueError:
        pass
        
    details = f"Q1: {q1}, Q2: {q2}, Q3: {q3}"
    
    new_assessment = Assessment(name=name, email=email, company=company, score=score, details=details)
    db.session.add(new_assessment)
    db.session.commit()
    
    return render_template('assessment_result.html', score=score, name=name)

if __name__ == '__main__':
    app.run(debug=True, port=5000)
